class_name CameraStateConfiguration

const VALID_TRANSITIONS: Dictionary = {
	STATE.ASSET.READY: 			[
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.FREELOOK_MOVE,
				STATE.ASSET.DISABLED
	],
	STATE.ASSET.IS_TRACKING: 	[
				STATE.ASSET.READY,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.FREELOOK_MOVE,
				STATE.ASSET.DISABLED
	],
	STATE.ASSET.TRACKING_FULL: 	[
				STATE.ASSET.READY,
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.FREELOOK_MOVE,
				STATE.ASSET.DISABLED
	],
	STATE.ASSET.TRACKING_POS: 	[
				STATE.ASSET.READY,
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.FREELOOK_MOVE,
				STATE.ASSET.DISABLED
	],	
	STATE.ASSET.TRACKING_FREE: 	[
				STATE.ASSET.READY,
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.FREELOOK_MOVE,
				STATE.ASSET.DISABLED
	],
	STATE.ASSET.IDLE_ROTATE: 	[
				STATE.ASSET.READY,
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.FREELOOK_MOVE,
				STATE.ASSET.DISABLED
	],
	STATE.ASSET.IS_FREELOOK: 	[
				STATE.ASSET.READY,
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.FREELOOK_MOVE,
				STATE.ASSET.DISABLED
	],
	STATE.ASSET.FREELOOK_MOVE: 	[
				STATE.ASSET.READY,
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.DISABLED
	],
	STATE.ASSET.DISABLED: 		[
				STATE.ASSET.READY,
				STATE.ASSET.IS_TRACKING,
				STATE.ASSET.TRACKING_FULL,
				STATE.ASSET.TRACKING_POS,
				STATE.ASSET.TRACKING_FREE,
				STATE.ASSET.IDLE_ROTATE,
				STATE.ASSET.IS_FREELOOK,
				STATE.ASSET.FREELOOK_MOVE
	]
}

const SPIN_VALUES: Dictionary = {
	STATE.ASSET.IDLE_ROTATE: CameraConfig.DEFAULTS.IDLE_ROTATE_SPEED
}
