class_name ThrowableStateConfiguration

const WINDOW_VALUES: Dictionary = {
	ItemState.STATE.READY: 0,
	ItemState.STATE.WINDUP_UNDERCOOKED: 0.3,
	ItemState.STATE.WINDUP_VERY_EARLY: 0.6,
	ItemState.STATE.WINDUP_EARLY: 1,
	ItemState.STATE.WINDUP_PERFECT: 1.3,
	ItemState.STATE.WINDUP_LATE: 1.6,
	ItemState.STATE.WINDUP_VERY_LATE: 2,
	ItemState.STATE.WINDUP_OVERCOOKED: 2.3
}

const VALID_TRANSITIONS: Dictionary = {
	self.STATE.READY: 	[
				self.STATE.WINDUP_UNDERCOOKED,
				self.STATE.WINDUP_VERY_EARLY,
				self.STATE.WINDUP_EARLY,
				self.STATE.WINDUP_PERFECT,
				self.STATE.WINDUP_LATE,
				self.STATE.WINDUP_VERY_LATE,
				self.STATE.WINDUP_OVERCOOKED
	],
	self.STATE.WINDUP_UNDERCOOKED: [self.STATE.READY, self.STATE.WINDUP_VERY_EARLY, self.STATE.THROWING_UNDER],
	self.STATE.WINDUP_VERY_EARLY: [self.STATE.READY, self.STATE.WINDUP_EARLY, self.STATE.THROWING_UNDER],
	self.STATE.WINDUP_EARLY: [self.STATE.READY, self.STATE.WINDUP_PERFECT, self.STATE.THROWING_UNDER],
	self.STATE.WINDUP_PERFECT: [self.STATE.READY, self.STATE.WINDUP_LATE, self.STATE.THROWING_PERFECT],
	self.STATE.WINDUP_LATE: [self.STATE.READY, self.STATE.WINDUP_VERY_LATE, self.STATE.THROWING_OVER],
	self.STATE.WINDUP_VERY_LATE: [self.STATE.READY, self.STATE.WINDUP_OVERCOOKED, self.STATE.THROWING_OVER],
	self.STATE.WINDUP_OVERCOOKED: [self.STATE.READY, self.STATE.THROWING_OVER],
	self.STATE.THROWING_UNDER: [self.STATE.READY, self.STATE.FOLLOW_THRU_UNDER],
	self.STATE.THROWING_PERFECT: [self.STATE.READY, self.STATE.FOLLOW_THRU_PERFECT],
	self.STATE.THROWING_OVER: [self.STATE.READY, self.STATE.FOLLOW_THRU_OVER],
	self.STATE.FOLLOW_THRU_UNDER: [self.STATE.READY],
	self.STATE.FOLLOW_THRU_PERFECT: [self.STATE.READY],
	self.STATE.FOLLOW_THRU_OVER: [self.STATE.READY]
}

const SPIN_VALUES: Dictionary = {
	ItemState.STATE.READY: 0,
	ItemState.STATE.WINDUP_UNDERCOOKED: 0.2,
	ItemState.STATE.WINDUP_VERY_EARLY: 0.3,
	ItemState.STATE.WINDUP_EARLY: .6,
	ItemState.STATE.WINDUP_PERFECT: 1.0,
	ItemState.STATE.WINDUP_LATE: 1.4,
	ItemState.STATE.WINDUP_VERY_LATE: 1.7,
	ItemState.STATE.WINDUP_OVERCOOKED: 2.0
}
