class_name ThrowableStateConfiguration


# TODO None of this shit is right anymore; all of those constants have moved

const WINDOW_VALUES: Dictionary = {
	STATE.ASSET.READY: 0,
	STATE.ASSET.WINDUP_UNDERCOOKED: 0.3,
	STATE.ASSET.WINDUP_VERY_EARLY: 0.6,
	STATE.ASSET.WINDUP_EARLY: 1,
	STATE.ASSET.WINDUP_PERFECT: 1.3,
	STATE.ASSET.WINDUP_LATE: 1.6,
	STATE.ASSET.WINDUP_VERY_LATE: 2,
	STATE.ASSET.WINDUP_OVERCOOKED: 2.3
}

const VALID_TRANSITIONS: Dictionary = {
	STATE.ASSET.READY: 	[
				STATE.ASSET.WINDUP_UNDERCOOKED,
				STATE.ASSET.WINDUP_VERY_EARLY,
				STATE.ASSET.WINDUP_EARLY,
				STATE.ASSET.WINDUP_PERFECT,
				STATE.ASSET.WINDUP_LATE,
				STATE.ASSET.WINDUP_VERY_LATE,
				STATE.ASSET.WINDUP_OVERCOOKED
	],
	STATE.ASSET.WINDUP_UNDERCOOKED: [
				STATE.ASSET.READY, 
				STATE.ASSET.WINDUP_VERY_EARLY, 
				STATE.ASSET.THROWING_UNDER
	],
	STATE.ASSET.WINDUP_VERY_EARLY: [
				STATE.ASSET.READY,
				STATE.ASSET.WINDUP_EARLY,
				STATE.ASSET.THROWING_UNDER
	],
	STATE.ASSET.WINDUP_EARLY: [
				STATE.ASSET.READY, 
				STATE.ASSET.WINDUP_PERFECT, 
				STATE.ASSET.THROWING_UNDER
	],
	STATE.ASSET.WINDUP_PERFECT: [
				STATE.ASSET.READY, 
				STATE.ASSET.WINDUP_LATE, 
				STATE.ASSET.THROWING_PERFECT
	],
	STATE.ASSET.WINDUP_LATE: [
				STATE.ASSET.READY, 
				STATE.ASSET.WINDUP_VERY_LATE, 
				STATE.ASSET.THROWING_OVER
	],
	STATE.ASSET.WINDUP_VERY_LATE: [
				STATE.ASSET.READY, 
				STATE.ASSET.WINDUP_OVERCOOKED, 
				STATE.ASSET.THROWING_OVER
	],
	STATE.ASSET.WINDUP_OVERCOOKED: [
				STATE.ASSET.READY, 
				STATE.ASSET.THROWING_OVER
	],
	STATE.ASSET.THROWING_UNDER: [
				STATE.ASSET.READY, 
				STATE.ASSET.FOLLOW_THRU_UNDER
	],
	STATE.ASSET.THROWING_PERFECT: [
				STATE.ASSET.READY, 
				STATE.ASSET.FOLLOW_THRU_PERFECT
	],
	STATE.ASSET.THROWING_OVER: [
				STATE.ASSET.READY, 
				STATE.ASSET.FOLLOW_THRU_OVER
	],
	STATE.ASSET.FOLLOW_THRU_UNDER: [STATE.ASSET.READY],
	STATE.ASSET.FOLLOW_THRU_PERFECT: [STATE.ASSET.READY],
	STATE.ASSET.FOLLOW_THRU_OVER: [STATE.ASSET.READY]
}

const SPIN_VALUES: Dictionary = {
	STATE.ASSET.READY: 0,
	STATE.ASSET.WINDUP_UNDERCOOKED: 0.2,
	STATE.ASSET.WINDUP_VERY_EARLY: 0.3,
	STATE.ASSET.WINDUP_EARLY: .6,
	STATE.ASSET.WINDUP_PERFECT: 1.0,
	STATE.ASSET.WINDUP_LATE: 1.4,
	STATE.ASSET.WINDUP_VERY_LATE: 1.7,
	STATE.ASSET.WINDUP_OVERCOOKED: 2.0
}
