extends Node

class_name GLOBAL_SETTINGS

# TODO This class should be refactored to exist somewhere else; These values belong in other files
#		CONTROLS stuff should really exist in USER_INPUT
#		Other stuff should exist in option_menu.gd or somewhere else

const PLAYER = {
	"RUN_SPEED": 5.0,
	"SPRINT_SPEED": 4.0,
	"JUMP_FORCE": 4.5, 
	"MAX_LAUNCH_ROTATION": 67,
	"MIN_LAUNCH_ROTATION": -25
}

const DISK = {
	"LAUNCH_SPEED": 10,
	"MAX_HOLD": 2,
	"HOLD_MULTIPLIER": 1.5,
	"GRAVITY_MULTIPLIER": .009,
	"MAX_PULL": 200,
	"MIN_PULL": 15,
	"MAX_OFFSET": 400
}

const CAMERA_DEFAULTS = {
	"PAN_SPEED": .15,
	"ROTATE_SPEED": 4,
	"IDLE_ROTATE_SPEED": 25.0,
	"MIN_HEIGHT": 4,
	"SHOT_WATCH_TIME": 5,
	CONSTANTS.FOV: 90,
	CONSTANTS.IN_ADJUST: 20,
	CONSTANTS.OUT_ADJUST: 5
}
static var CAMERA = CAMERA_DEFAULTS.duplicate()

# TODO Missing player interact button
const CONTROLS_DEFAULTS =  {
	USER_INPUT.MOVE.ROTATE_LEFT: KEY_A,
	USER_INPUT.MOVE.ROTATE_RIGHT: KEY_D,
	USER_INPUT.MOVE.FORWARD: KEY_W,
	USER_INPUT.MOVE.BACKWARD: KEY_S,
	USER_INPUT.MOVE.STRAFE_LEFT: KEY_Q,
	USER_INPUT.MOVE.STRAFE_RIGHT: KEY_E,
	USER_INPUT.MOVE.JUMP: KEY_SPACE,
	USER_INPUT.MOVE.CROUCH: KEY_CTRL,
	USER_INPUT.MOVE.SPRINT: KEY_SHIFT,
	USER_INPUT.ACTION.PRIMARY: MOUSE_BUTTON_LEFT,
	USER_INPUT.ACTION.SECONDARY: MOUSE_BUTTON_RIGHT,
	USER_INPUT.ACTION.INTERACT: KEY_F,
	USER_INPUT.MOVE.ROTATE_UP: MOUSE_BUTTON_WHEEL_UP,
	USER_INPUT.MOVE.ROTATE_DOWN: MOUSE_BUTTON_WHEEL_DOWN,
	USER_INPUT.MENU.SCORE: KEY_TAB,
	USER_INPUT.MENU.MAIN: KEY_ESCAPE,
	USER_INPUT.ADMIN.DEBUG: KEY_PAGEDOWN,
	CONSTANTS.HORIZONTAL_AIM_SENSITIVITY: 1.5,
	CONSTANTS.HORIZONTAL_LOOK_SENSITIVITY: 1.5,
	CONSTANTS.VERTICAL_AIM_SENSITIVITY: .5,
	CONSTANTS.VERTICAL_LOOK_SENSITIVITY: .5,
	CONSTANTS.INVERT_HORIZONTAL: false,
	CONSTANTS.INVERT_VERTICAL: false
}
static var CONTROLS: Dictionary = CONTROLS_DEFAULTS.duplicate()

const DISPLAY_DEFAULTS = {
	CONSTANTS.PERFORMANCE: false
}
static var DISPLAY = DISPLAY_DEFAULTS.duplicate()

const MENU = {
	"SCORECARD": {
		"PLAYER_PIXEL_SIZE": .003,
		"TEEBOX_PIXEL_SIZE": .0023
	}
}

const COLOR = {
	"CHARGE": Color.RED,
	"PATH": Color.BLUE
}

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta: float) -> void:
	pass
