extends Node

class_name GLOBAL_SETTINGS

const PLAYER: Dictionary = {
	"RUN_SPEED": 5.0,
	"SPRINT_SPEED": 4.0,
	"JUMP_FORCE": 4.5, 
	"MAX_LAUNCH_ROTATION": 67,
	"MIN_LAUNCH_ROTATION": -25
}

const DISK: Dictionary = {
	"LAUNCH_SPEED": 10,
	"MAX_HOLD": 2,
	"HOLD_MULTIPLIER": 1.5,
	"GRAVITY_MULTIPLIER": .009,
	"MAX_PULL": 200,
	"MIN_PULL": 15,
	"MAX_OFFSET": 400
}

const CAMERA_DEFAULTS: Dictionary = {
	"PAN_SPEED": .15,
	"ROTATE_SPEED": 4,
	"IDLE_ROTATE_SPEED": 25.0,
	"MIN_HEIGHT": 4,
	"SHOT_WATCH_TIME": 5,
	CONSTANTS.FOV: 90,
	CONSTANTS.IN_ADJUST: 20,
	CONSTANTS.OUT_ADJUST: 5
}
static var CAMERA = CAMERA_DEFAULTS.duplicate()

# TODO Maybe try explicit type casting out of the dictionary
const CONTROLS_DEFAULTS: Dictionary =  {
	CONSTANTS.USER_INPUT.ROTATE_LEFT: KEY_A,
	CONSTANTS.USER_INPUT.ROTATE_RIGHT: KEY_D,
	CONSTANTS.USER_INPUT.FORWARD: KEY_W,
	CONSTANTS.USER_INPUT.BACKWARD: KEY_S,
	CONSTANTS.USER_INPUT.STRAFE_LEFT: KEY_Q,
	CONSTANTS.USER_INPUT.STRAFE_RIGHT: KEY_E,
	CONSTANTS.USER_INPUT.JUMP: KEY_SPACE,
	CONSTANTS.USER_INPUT.CROUCH: KEY_CTRL,
	CONSTANTS.USER_INPUT.SPRINT: KEY_SHIFT,
	CONSTANTS.USER_INPUT.PRIMARY: MOUSE_BUTTON_LEFT,
	CONSTANTS.USER_INPUT.SECONDARY: MOUSE_BUTTON_RIGHT,
	CONSTANTS.USER_INPUT.INTERACT: KEY_F,
	CONSTANTS.USER_INPUT.ROTATE_UP: MOUSE_BUTTON_WHEEL_UP,
	CONSTANTS.USER_INPUT.ROTATE_DOWN: MOUSE_BUTTON_WHEEL_DOWN,
	CONSTANTS.USER_INPUT.SCORE: KEY_TAB,
	CONSTANTS.USER_INPUT.MAIN: KEY_ESCAPE,
	CONSTANTS.USER_INPUT.DEBUG: KEY_PAGEDOWN,
	CONSTANTS.HORIZONTAL_AIM_SENSITIVITY: 1.5,
	CONSTANTS.HORIZONTAL_LOOK_SENSITIVITY: 1.5,
	CONSTANTS.VERTICAL_AIM_SENSITIVITY: .5,
	CONSTANTS.VERTICAL_LOOK_SENSITIVITY: .5,
	CONSTANTS.INVERT_HORIZONTAL: false,
	CONSTANTS.INVERT_VERTICAL: false
}
static var CONTROLS: Dictionary = CONTROLS_DEFAULTS.duplicate()

const DISPLAY_DEFAULTS: Dictionary = {
	CONSTANTS.PERFORMANCE: false
}
static var DISPLAY = DISPLAY_DEFAULTS.duplicate()

const COLOR: Dictionary = {
	"CHARGE": Color.RED,
	"PATH": Color.BLUE
}

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	pass

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta: float) -> void:
	pass
